StaskoFy/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StaskoFy.Core.IService;
using StaskoFy.Models.Entities;
using StaskoFy.ViewModels.Album;
using System.Security.Claims;
using System.Threading.Tasks;

namespace StaskoFy.Controllers
{
    public class AlbumController : Controller
    {
        private readonly IAlbumService albumService;
        private readonly IArtistService artistService;
        private readonly ISongService songService;

        public AlbumController(IAlbumService _albumService, IArtistService _artistService, ISongService _songService)
        {
            this.albumService = _albumService;
            this.artistService = _artistService;
            this.songService = _songService;
        }

        [HttpGet]
        [Authorize(Policy = "Artist")]
        public async Task<IActionResult> AlbumsIndexForCurrentLoggedArtist(string searchItem, List<string> filters)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var albums = await albumService.FilterAlbumsForCurrentLoggedArtistAsync(Guid.Parse(userId), searchItem, filters);

            if (!albums.Any())
            {
                ViewData["NoResult"] = "No albums found matching your search.";
            }

            return View(albums);
        }

        [HttpGet]
        [Authorize(Policy = "ArtistOrUser")]
        public async Task<IActionResult> AlbumsIndexForAllUsers(string searchItem, List<string> filters)
        {
            var albums = await albumService.FilterAlbumsAsync(searchItem, filters);

            if (!albums.Any())
            {
                ViewData["NoResult"] = "No albums found matching your search.";
            }

            return View(albums);
        }

        [HttpGet]
        [Authorize(Policy = "Artist")]
        public async Task<ActionResult> Create()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var artists = await artistService.PopulateArtistSelectListAsync(Guid.Parse(userId));
            var songs = await songService.SelectSongsByCurrentLoggedArtistAsync(Guid.Parse(userId));

            var model = new AlbumCreateViewModel
            {
                Artists = new MultiSelectList(artists, "Id", "Username"),
                Songs = new MultiSelectList(songs, "Id", "Title"),
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "Artist")]
        public async Task<IActionResult> Create(AlbumCreateViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (!ModelState.IsValid)
            {
                var artists = await artistService.PopulateArtistSelectListAsync(Guid.Parse(userId));
                model.Artists = new MultiSelectList(artists, "Id", "Username");

                var songs = await songService.SelectSongsByCurrentLoggedArtistAsync(Guid.Parse(userId));
                model.Songs = new MultiSelectList(songs, "Id", "Title");

                return View(model);
            }

            await albumService.AddAlbumAsync(model, Guid.Parse(userId));
            return RedirectToAction("AlbumsIndexForCurrentLoggedArtist");
        }

        [HttpGet]
        [Authorize(Policy = "Artist")]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            var album = await albumService.GetAlbumByIdAsync(id);

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var artists = await artistService.PopulateArtistSelectListAsync(Guid.Parse(userId));
            var songs = await songService.SelectSongsByCurrentLoggedArtistAsync(Guid.Parse(userId));

            var model = new AlbumEditViewModel
            {
                Id = album.Id,
                Title = album.Title,
                ReleaseDate = album.ReleaseDate,
                ImageURL = album.ImageURL,
                Artists = new MultiSelectList(artists, "Id", "Username"),
                Songs = new MultiSelectList(songs, "Id", "Title"),
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "Artist")]
        public async Task<IActionResult> Edit(AlbumEditViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (!ModelState.IsValid)
            {
                var artists = await artistService.PopulateArtistSelectListAsync(Guid.Parse(userId));
                model.Artists = new MultiSelectList(artists, "Id", "Username");
                
                var songs = await songService.SelectSongsByCurrentLoggedArtistAsync(Guid.Parse(userId));
                model.Songs = new MultiSelectList(songs, "Id", "Title");
                
                return View(model);
            }

            await albumService.UpdateAlbumAsync(model, Guid.Parse(userId));
            return RedirectToAction("AlbumsIndexForCurrentLoggedArtist");
        }

        [HttpPost]
        [Authorize(Policy = "Artist")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            await albumService.RemoveAlbumAsync(id);
            return RedirectToAction("AlbumsIndexForCurrentLoggedArtist");
        }

        [HttpGet]
        [Authorize(Policy = "ArtistOrUser")]
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            var album = await albumService.GetAlbumByIdWithSongsAsync(id);

            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }
    }
}

StaskoFy/Controllers/GenreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StaskoFy.Core.IService;
using StaskoFy.ViewModels.Genre;

namespace StaskoFy.Controllers
{
    public class GenreController : Controller
    {
        private readonly IGenreService genreService;

        public GenreController(IGenreService _genreService)
        {
            this.genreService = _genreService;
        }

        [HttpGet]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Index()
        {
            var genres = await genreService.GetGenresAsync();

            return View(genres);
        }

        [HttpGet]
        [Authorize(Policy = "Admin")]
        public IActionResult Create()
        {
            var model = new GenreCreateViewModel();
            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Create(GenreCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await genreService.AddGenreAsync(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            var genre = await genreService.GetGenreByIdAsync(id);

            if (genre == null)
            {
                return NotFound();
            }

            var model = new GenreEditViewModel
            {
                Id = genre.Id,
                Name = genre.Name,
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Edit(GenreEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await genreService.UpdateGenreAsync(model);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            var genre = await genreService.GetGenreByIdAsync(id);

            if (genre == null)
            {
                return NotFound();
            }

            await genreService.RemoveGenreAsync(id);
            return RedirectToAction("Index");
        }
    }
}

StaskoFy/Controllers/LibraryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StaskoFy.Core.IService;
using StaskoFy.ViewModels.Library;
using StaskoFy.ViewModels.LikedSongs;
using StaskoFy.ViewModels.Playlist;
using System.Security.Claims;
namespace StaskoFy.Controllers
{
    public class LibraryController : Controller
    {

        private readonly IPlaylistService playlistService;
        private readonly ILikedSongsService likedSongsService;

        public LibraryController(IPlaylistService _playlistService, ILikedSongsService _likedSongsService)
        {
            this.playlistService = _playlistService;
            this.likedSongsService = _likedSongsService;
        }

        [HttpGet]
        [Authorize(Policy = "ArtistOrUser")]
        public async Task<IActionResult> MyLibraryIndex()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var playlists = await playlistService.GetPlaylistsFromCurrentLoggedUserAsync(Guid.Parse(userId));
            var likedSongs = await likedSongsService.GetLikedSongsFromCurrentLoggedUserAsync(Guid.Parse(userId));

            var viewModel = new LibraryViewModel
            {
                Playlists = new List<PlaylistIndexViewModel>(playlists),
                LikedSongs = new List<LikedSongsIndexViewModel>(likedSongs)
            };

            return View(viewModel);
        }
    }
}

StaskoFy/Controllers/SongController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StaskoFy.Core.IService;
using StaskoFy.ViewModels.Song;
using System.Security.Claims;

namespace StaskoFy.Controllers
{
    public class SongController : Controller
    {
        private readonly ISongService songService;
        private readonly IGenreService genreService;
        private readonly IArtistService artistService;
        private readonly IImageService imageService;

        public SongController(ISongService _songService, IGenreService _genreService, IArtistService _artistService, IImageService _imageService)
        {
            this.songService = _songService;
            this.genreService = _genreService;
            this.artistService = _artistService;
            this.imageService = _imageService;
        }

        [HttpGet]
        [Authorize(Policy = "Artist")]
        public async Task<IActionResult> SongsIndexForCurrentLoggedArtist(string searchItem, List<string> filters)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var songs = await songService.FilterSongsForCurrentLoggedArtistAsync(Guid.Parse(userId), searchItem, filters);

            if (!songs.Any())
            {
                ViewData["NoResult"] = "No songs found matching your search.";
            }

            return View(songs);
        }

        [HttpGet]
        [Authorize(Policy = "ArtistOrUser")]
        public async Task<IActionResult> SongsIndexForAllUsers(string searchItem, List<string> filters)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var songs = await songService.FilterSongsAsync(searchItem, filters);

            if (!songs.Any())
            {
                ViewData["NoResult"] = "No songs found matching your search.";
            }

            return View(songs);
        }

        [HttpGet]
        [Authorize(Policy = "Artist")]
        public async Task<IActionResult> Create()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var genres = await genreService.GetGenresAsync();
            ViewBag.Genres = new SelectList(genres, "Id", "Name");

            var artists = await artistService.PopulateArtistSelectListAsync(Guid.Parse(userId));
            var model = new SongCreateViewModel
            {
                Artists = new MultiSelectList(artists, "Id", "Username")
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "Artist")]
        public async Task<IActionResult> Create(SongCreateViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (!ModelState.IsValid)
            {
                var genres = await genreService.GetGenresAsync();
                ViewBag.Genres = new SelectList(genres, "Id", "Name");

                var artists = await artistService.PopulateArtistSelectListAsync(Guid.Parse(userId));
                model.Artists = new MultiSelectList(artists, "Id", "Username");

                return View(model);
            }

            var uploadResult = await imageService.UploadImageAsync(model.ImageFile, model.ImageFile.FileName, "songs");

            await songService.AddSongAsync(model, Guid.Parse(userId), uploadResult.Url, uploadResult.PublicId);
            return RedirectToAction("SongsIndexForCurrentLoggedArtist");
        }

        [HttpGet]
        [Authorize(Policy = "Artist")]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var genres = await genreService.GetGenresAsync();
            ViewBag.Genres = new SelectList(genres, "Id", "Name");

            var artists = await artistService.PopulateArtistSelectListAsync(Guid.Parse(userId));

            var song = await songService.GetSongByIdAsync(id);

            if (song == null)
            {
                return NotFound();
            }

            var model = new SongEditViewModel
            {
                Id = song.Id,
                Title = song.Title,
                Minutes = song.Minutes,
                Seconds = song.Seconds,
                ReleaseDate = song.ReleaseDate,
                GenreId = song.GenreId,
                ImageURL = song.ImageURL,
                Artists = new MultiSelectList(artists, "Id", "Username")
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "Artist")]
        public async Task<IActionResult> Edit(SongEditViewModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (!ModelState.IsValid)
            {
                var genres = await genreService.GetGenresAsync();
                ViewBag.Genres = new SelectList(genres, "Id", "Name");

                var artists = await artistService.PopulateArtistSelectListAsync(Guid.Parse(userId));
                model.Artists = new MultiSelectList(artists, "Id", "Username");

                return View(model);
            }

            await songService.UpdateSongsAsync(model, Guid.Parse(userId));
            return RedirectToAction("SongsIndexForCurrentLoggedArtist");
        }

        [HttpPost]
        [Authorize(Policy = "Artist")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            var song = await songService.GetSongByIdAsync(id);

            if (song == null)
            {
                return NotFound();
            }

            if (!string.IsNullOrEmpty(song.CloudinaryPublicId))
            {
                await imageService.DestroyImageAsync(song.CloudinaryPublicId);
            }

            await songService.RemoveSongAsync(id);
            return RedirectToAction("SongsIndexForCurrentLoggedArtist");
        }
    }
}

StaskoFy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StaskoFy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StaskoFy.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-pV3L+3yxGr6pXKZpL+qvWQFdybgQbsA3R1Rl1M1lQ+k0G5Y/J44l3rDrYy/+YpzA0d1GfD0ZwW2bNyzOOk+6xA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">StaskoFy</a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640" width="30" height="30" class="me-2"><!--!Font Awesome Free v7.2.0 by @@fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2026 Fonticons, Inc.--><path fill="rgb(255, 255, 255)" d="M304 70.1C313.1 61.9 326.9 61.9 336 70.1L568 278.1C577.9 286.9 578.7 302.1 569.8 312C560.9 321.9 545.8 322.7 535.9 313.8L527.9 306.6L527.9 511.9C527.9 547.2 499.2 575.9 463.9 575.9L175.9 575.9C140.6 575.9 111.9 547.2 111.9 511.9L111.9 306.6L103.9 313.8C94 322.6 78.9 321.8 70 312C61.1 302.2 62 287 71.8 278.1L304 70.1zM320 120.2L160 263.7L160 512C160 520.8 167.2 528 176 528L224 528L224 424C224 384.2 256.2 352 296 352L344 352C383.8 352 416 384.2 416 424L416 528L464 528C472.8 528 480 520.8 480 512L480 263.7L320 120.3zM272 528L368 528L368 424C368 410.7 357.3 400 344 400L296 400C282.7 400 272 410.7 272 424L272 528z" /></svg></a>
                        </li>
                        @if ((User?.Identity?.IsAuthenticated ?? false) && (User.IsInRole("Admin")))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage Genres</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-white" asp-controller="Genre" asp-action="Index">View genres</a>
                                    <a class="dropdown-item text-white" asp-controller="Genre" asp-action="Create">Create genre</a>
                                </div>
                            </li>
                        }
                        else if ((User?.Identity?.IsAuthenticated ?? false) && (User.IsInRole("Artist")))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Songs</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-white" asp-controller="Song" asp-action="SongsIndexForCurrentLoggedArtist">View your songs</a>
                                    <a class="dropdown-item text-white" asp-controller="Song" asp-action="Create">Create a song</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Albums</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-white" asp-controller="Album" asp-action="AlbumsIndexForCurrentLoggedArtist">View your albums</a>
                                    <a class="dropdown-item text-white" asp-controller="Album" asp-action="Create">Create an album</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Song" asp-action="SongsIndexForAllUsers">Browse Songs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Album" asp-action="AlbumsIndexForAllUsers">Browse Albums</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Library" asp-action="MyLibraryIndex">My Library</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Artist" asp-action="Index">Artists</a>
                            </li>
                        }
                        else if ((User?.Identity?.IsAuthenticated ?? false) && (User.IsInRole("User")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Song" asp-action="SongsIndexForAllUsers">Browse Songs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Album" asp-action="AlbumsIndexForAllUsers">Browse Albums</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Library" asp-action="MyLibraryIndex">My Library</a>
                            </li>
                        }
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - StaskoFy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>